AWS_REGION="us-west-1"

# Dynamically generated by TF
export MODEL_BUCKET_PROD="my-stg-mlflow-models-mlops-zoomcamp"
export PREDICTIONS_STREAM_NAME="my-stg-ride-predictions-mlops-zoomcamp"
export LAMBDA_FUNCTION="my-stg-prediction-lambda_mlops-zoomcamp"

# Model artifacts bucket from the previous weeks (MLflow experiments)
export MODEL_BUCKET_DEV="mlflow-models-alexey"

export RUN_ID="c89bbf86b5a5486a9eb90a880c4a6a16"

# Just mocking the artifacts from training process in the Prod env
aws s3 cp ../mlflow.db s3://${MODEL_BUCKET_PROD}
aws s3 sync ../mlruns s3://${MODEL_BUCKET_PROD}/mlruns

# Set new var RUN_ID in existing set of vars.
variables="{PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}, MODEL_BUCKET=${MODEL_BUCKET_PROD}, RUN_ID=${RUN_ID}}"

# https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
aws lambda update-function-configuration --function-name ${LAMBDA_FUNCTION} --environment "Variables=${variables}"
