source_stream_name = "my-stg-ride-events"
output_stream_name = "my-stg-ride-predictions"
model_bucket = "my-stg-mlflow-models"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "my-stg-stream-model-duration"
lambda_function_name = "my-stg-prediction-lambda"